<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SpineGen.Test</RootNamespace>
    <AssemblyName>SpineGen.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableDefaultEmbeddedResourceItems>true</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpineGen.Drawing.System.Drawing\SpineGen.Drawing.System.Drawing.csproj" />
    <ProjectReference Include="..\SpineGen.JSON\SpineGen.JSON.csproj" />
    <ProjectReference Include="..\SpineGen\SpineGen.csproj" />
  </ItemGroup>

</Project>
