<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Целевая платформа -->
		<TargetFramework>net8.0-windows</TargetFramework>

		<!-- Разрешаем unsafe код (требуется для DataConverter.cs и LZMA) -->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- СОХРАНЯЕМ СТАРУЮ КОНСТАНТУ ИЗ СТАРОГО ПРОЕКТА! 
    Иначе код начнет компилироваться с другой логикой. -->
		<DefineConstants>$(DefineConstants);DISABLE_TRACE</DefineConstants>

		<!-- Исключаем PDF и текстовые файлы из сборки, чтобы они не копировались в bin\Debug -->
		<DefaultItemExcludes>$(DefaultItemExcludes);Doc\**;ToDo.txt;LICENSE</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>
		<!-- В .NET 8 System.Data.DataSetExtensions больше не существует, 
    но если какой-то код использует DataSet, подключаем стандартный System.Data -->
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

</Project>