name: Build and Release .NET Desktop App

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      solution: 'hakchi_gui.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          submodules: true

      - name: Install NSIS
        run: choco install nsis -y --no-progress

      - name: Add NSIS to PATH
        run: echo "C:\Program Files (x86)\NS